# Generated by Django 2.0.5 on 2018-06-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=32)),
                ('college', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('facebook_url', models.CharField(max_length=256)),
                ('profile_picture', models.CharField(max_length=512)),
                ('dept_id', models.IntegerField()),
                ('sub1_id', models.IntegerField()),
                ('sub2_id', models.IntegerField()),
                ('sub3_id', models.IntegerField()),
                ('sub1', models.IntegerField()),
                ('sub2', models.IntegerField()),
                ('sub3', models.IntegerField()),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
